# Generated by Django 5.2 on 2026-08-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0002_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('vehicles', '0002_alter_brand_options_alter_vehiclemodel_options_and_more'),
        ('wash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WashJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('washing', 'Washing'), ('quality_check', 'Quality Check'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('quality_notes', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quality_check_at', models.DateTimeField(blank=True, null=True)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='wash_photos/before/')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='wash_photos/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wash_jobs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_jobs', to='bookings.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wash_jobs', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wash_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wash_jobs', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_jobs', to='invoices.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_jobs', to='orders.order')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_jobs', to='services.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wash_jobs', to='vehicles.vehicle')),
                ('wash_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_jobs', to='wash.washbay')),
            ],
            options={
                'db_table': 'wash_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='wash_jobs_status_1e30e4_idx'), models.Index(fields=['branch', 'status'], name='wash_jobs_branch__46dfe5_idx'), models.Index(fields=['assigned_employee'], name='wash_jobs_assigne_bc0fca_idx')],
            },
        ),
    ]
