# Generated by Django 5.2 on 2026-08-05 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_product_reorder_quantity_and_more'),
        ('services', '0001_initial'),
        ('wash', '0002_washjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('repair', 'Repair'), ('product', 'Product'), ('other', 'Other')], default='service', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('wash_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wash.washjob')),
            ],
            options={
                'db_table': 'wash_job_items',
                'ordering': ['created_at'],
            },
        ),
    ]
