# Generated by Django 5.2 on 2026-08-05 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode_product_reorder_quantity_and_more'),
        ('wash', '0003_washjobitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='washjob',
            name='checklist_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='checklist_exterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='checklist_interior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='checklist_vacuum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='checklist_wheels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='checklist_windows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='washjob',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, help_text='Estimated time car will be ready.', null=True),
        ),
        migrations.AddField(
            model_name='washjob',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_job_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Estimated repair time in hours.', max_digits=5),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='technician_notes',
            field=models.TextField(blank=True, help_text='Internal notes for technician.'),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='vat_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='washjobitem',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0, help_text='Warranty period in days. 0 = no warranty.'),
        ),
        migrations.AlterField(
            model_name='washjobitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('repair', 'Repair'), ('product', 'Product'), ('custom', 'Custom')], default='service', max_length=20),
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('vehicle_reg', models.CharField(max_length=50)),
                ('vehicle_desc', models.CharField(blank=True, max_length=255)),
                ('items_summary', models.TextField(blank=True, help_text='List of services/repairs being done.')),
                ('estimated_time', models.CharField(blank=True, help_text='e.g., "2-3 hours", "Ready by 4 PM"', max_length=100)),
                ('special_instructions', models.TextField(blank=True, help_text='Customer special requests.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, help_text='Name of person who collected the vehicle.', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wash_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_note', to='wash.washjob')),
            ],
            options={
                'db_table': 'job_notes',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='wash.washjobitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_parts_used', to='inventory.product')),
            ],
            options={
                'db_table': 'repair_parts',
                'ordering': ['created_at'],
            },
        ),
    ]
