# Generated by Django 5.2 on 2026-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Business Name', help_text='Business trading name displayed on receipts and UI.', max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Legal registered business name.', max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number.', max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Sri Lanka', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('phone2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Business logo. Displayed on receipts and UI.', null=True, upload_to='logos/')),
                ('tagline', models.CharField(blank=True, help_text='Short tagline shown on receipts.', max_length=255)),
                ('currency_code', models.CharField(default='LKR', help_text='ISO 4217 currency code. Default: LKR', max_length=10)),
                ('currency_symbol', models.CharField(default='Rs.', help_text='Currency symbol for display. Default: Rs.', max_length=10)),
                ('currency_name', models.CharField(default='Sri Lankan Rupee', max_length=100)),
                ('timezone', models.CharField(default='Asia/Colombo', max_length=100)),
                ('date_format', models.CharField(default='%d %b %Y', help_text='Python date format string.', max_length=50)),
                ('time_format', models.CharField(default='%I:%M %p', max_length=50)),
                ('print_format', models.CharField(choices=[('thermal_80mm', 'Thermal Receipt (80mm)'), ('dot_matrix', 'Dot Matrix'), ('half_a4', 'Half A4'), ('a4', 'A4')], default='thermal_80mm', help_text='Default print format for receipts and invoices.', max_length=50)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for choosing us!', help_text='Text printed at the bottom of every receipt.')),
                ('show_tax_on_receipt', models.BooleanField(default=True)),
                ('show_logo_on_receipt', models.BooleanField(default=True)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('tax_name', models.CharField(blank=True, default='VAT', max_length=50)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'db_table': 'businesses',
            },
        ),
    ]
