# Generated by Django 5.2 on 2026-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='job_note_format',
            field=models.CharField(choices=[('thermal_80mm', 'Thermal Receipt (80mm)'), ('half_a4_bw', 'Half A4 (Black & White)')], default='thermal_80mm', help_text='Default format for Job Notes.', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='job_note_message',
            field=models.TextField(blank=True, default='Please present this note when collecting your vehicle.', help_text='Message printed on job notes.'),
        ),
        migrations.AddField(
            model_name='business',
            name='job_note_terms',
            field=models.TextField(blank=True, default='We are not responsible for items left inside the vehicle.', help_text='Terms & conditions on job notes.'),
        ),
    ]
