# Generated by Django 5.2 on 2026-08-03 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('WASHER', 'Washer'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTANT', 'Accountant')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True, help_text='System roles cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('database.configure', 'Configure Database'), ('database.test', 'Test Database Connection'), ('database.view', 'View Database Config'), ('system.health', 'View System Health'), ('system.settings', 'Manage System Settings'), ('backup.create', 'Create Backup'), ('backup.view', 'View Backups'), ('backup.download', 'Download Backup'), ('backup.delete', 'Delete Backup'), ('backup.restore', 'Restore Backup'), ('backup.schedule', 'Schedule Backups'), ('trash.view', 'View Trash'), ('trash.restore', 'Restore from Trash'), ('trash.permanent_delete', 'Permanently Delete'), ('audit.view', 'View Audit Logs'), ('users.manage', 'Manage Users'), ('roles.manage', 'Manage Roles'), ('business.configure', 'Configure Business'), ('branch.manage', 'Manage Branches'), ('customers.view', 'View Customers'), ('customers.create', 'Create Customers'), ('customers.edit', 'Edit Customers'), ('customers.delete', 'Delete Customers'), ('vehicles.view', 'View Vehicles'), ('vehicles.create', 'Create Vehicles'), ('vehicles.edit', 'Edit Vehicles'), ('vehicles.delete', 'Delete Vehicles'), ('services.view', 'View Services'), ('services.manage', 'Manage Services'), ('pos.access', 'Access POS'), ('pos.discount', 'Apply Discounts'), ('pos.refund', 'Process Refunds'), ('orders.view', 'View Orders'), ('orders.void', 'Void Orders'), ('invoices.view', 'View Invoices'), ('invoices.void', 'Void Invoices'), ('inventory.view', 'View Inventory'), ('inventory.manage', 'Manage Inventory'), ('inventory.adjust', 'Adjust Stock'), ('suppliers.view', 'View Suppliers'), ('suppliers.manage', 'Manage Suppliers'), ('employees.view', 'View Employees'), ('employees.manage', 'Manage Employees'), ('finance.view', 'View Finance'), ('finance.manage', 'Manage Expenses'), ('reports.view', 'View Reports'), ('reports.export', 'Export Reports'), ('wash.view', 'View Wash Board'), ('wash.manage', 'Manage Wash Jobs'), ('bookings.view', 'View Bookings'), ('bookings.manage', 'Manage Bookings'), ('memberships.view', 'View Memberships'), ('memberships.manage', 'Manage Memberships')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
