# Generated by Django 5.2 on 2026-08-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per Rs. 100 spent.', max_digits=10)),
                ('currency_per_point', models.DecimalField(decimal_places=2, default=1, help_text='Rupees value per point when redeeming.', max_digits=10)),
                ('min_points_to_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points required to redeem.')),
                ('max_redemption_percent', models.DecimalField(decimal_places=2, default=50, help_text='Max % of total that can be paid with points.', max_digits=5)),
                ('points_expiry_days', models.PositiveIntegerField(default=365, help_text='Points expire after this many days. 0 = never.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'loyalty_config',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Adjustment'), ('expire', 'Expired'), ('bonus', 'Bonus')], db_index=True, max_length=20)),
                ('points', models.IntegerField(help_text='Positive to earn, negative to redeem.')),
                ('balance_after', models.IntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_transactions', to='customers.customer')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='loyalty_tra_custome_82ca19_idx')],
            },
        ),
    ]
