# Generated by Django 5.2 on 2026-08-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='previous_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(default='django.db.backends.postgresql', max_length=100)),
                ('host', models.CharField(default='127.0.0.1', max_length=255)),
                ('port', models.CharField(default='5432', max_length=10)),
                ('db_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('ssl_mode', models.CharField(choices=[('disable', 'Disable'), ('allow', 'Allow'), ('prefer', 'Prefer (default)'), ('require', 'Require'), ('verify-ca', 'Verify CA'), ('verify-full', 'Verify Full')], default='prefer', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_last_known_good', models.BooleanField(default=False)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.CharField(blank=True, max_length=255)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_configs_applied', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
