# Generated by Django 5.2 on 2026-08-04 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='Validity in days.')),
                ('wash_count', models.PositiveIntegerField(default=10, help_text='Number of washes included. 0 = unlimited.')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount on non-included services.', max_digits=5)),
                ('color', models.CharField(default='#04a9f5', help_text='Display color for this plan.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'membership_plans',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('wash_count_total', models.PositiveIntegerField(default=0)),
                ('wash_count_used', models.PositiveIntegerField(default=0)),
                ('wash_count_remaining', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='memberships.membershipplan')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
